In [1]:
import numpy as np
import torch
import torch.nn as nn

In [9]:
N = 1
C = 1
H = W = 3
oC = 1
kh = kw = 2
input = torch.arange(N * C * H * W).view(N, C, H, W)
kernel = torch.arange(oC * C * kh * kw).view(oC, C, kh, kw)

oh, ow = (H - kh + 1), (W - kw + 1)
output = torch.zeros(N, oC, oh, ow)
for n in range(N):
    for oc in range(oC):
        for i in range(oh):
            for j in range(ow):
                output[n, oc, i, j] = torch.sum(kernel[oc] * input[n, :, i : (i + kh), j : (j + kw)])
                
print('input: \n{}'.format(input))
print('kernel: \n{}'.format(kernel))
print('output: \n{}'.format(output))

input: 
tensor([[[[0, 1, 2],
          [3, 4, 5],
          [6, 7, 8]]]])
kernel: 
tensor([[[[0, 1],
          [2, 3]]]])
output: 
tensor([[[[19., 25.],
          [37., 43.]]]])


In [14]:
conv = nn.Conv2d(C, oC, (kh, kw), bias=False)
conv.weight.data.copy_(kernel)
output = conv(input.float())
print('torch output: \n{}'.format(output))

torch output: 
tensor([[[[19., 25.],
          [37., 43.]]]], grad_fn=<ThnnConv2DBackward>)
